"""Streamlit front end.

Run:  streamlit run app/main.py

This file owns page flow only. It calls `RecipeChatbot.respond()` and
draws whatever comes back; it does no searching, no ranking, no
prompting. All rendering lives in `app/components.py`, all session
plumbing in `app/state.py`.
"""

from __future__ import annotations

import sys
from pathlib import Path

import streamlit as st

# Allow `streamlit run app/main.py` from the project root: Streamlit puts
# the script's own directory on sys.path, not the repo root.
PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from app import components, state  # noqa: E402

st.set_page_config(page_title="Recipe Assistant", page_icon="🍳",
                   layout="centered")


def handle_message(bot, conversation, message: str) -> dict:
    """One turn. Returns a renderable record.

    Any backend failure becomes an error turn rather than a crashed
    page: the chat history survives, and the user can keep going.
    """
    try:
        reply = bot.respond(message, conversation)
    except Exception as exc:  # noqa: BLE001
        return {
            "user": message,
            "text": f"Something went wrong handling that: "
                    f"{type(exc).__name__}: {exc}",
            "results": [],
            "selected": None,
            "error": True,
        }
    return {
        "user": message,
        "text": reply.text,
        "results": reply.results,
        "selected": reply.selected,
        "used_llm": reply.used_llm,
        "error": False,
    }


def handle_pantry(bot, request: dict) -> dict:
    """Run the sidebar form. Same turn shape, so history renders it."""
    have = ", ".join(request["have"])
    exclude = request["exclude"]
    label = f"I have: {have}" + (f" · not: {', '.join(exclude)}" if exclude else "")

    try:
        matches = bot.pantry.match(
            have=request["have"],
            exclude=exclude,
            top_k=bot.settings.default_top_k,
            assume_staples=request["assume_staples"],
        )
    except Exception as exc:  # noqa: BLE001
        return {"user": label, "text": f"Pantry search failed: "
                                       f"{type(exc).__name__}: {exc}",
                "results": [], "selected": None, "pantry": [], "error": True}

    if not matches:
        text = ("Nothing in the database comes close to that combination. "
                "Try dropping an ingredient, or add a common one.")
    else:
        complete = sum(1 for m in matches if m.is_complete)
        text = (f"You can make {complete} of these right now."
                if complete else "Nothing is a perfect fit, but these are close.")

    return {"user": label, "text": text, "results": [], "selected": None,
            "pantry": matches, "error": False}


def main() -> None:
    st.title("🍳 Recipe Assistant")

    with st.spinner("Loading the recipe index…"):
        bot, failure = state.load_bot()

    if failure is not None:
        components.render_load_failure(failure)
        st.stop()

    components.render_sidebar(bot)
    if st.sidebar.button("Start over", use_container_width=True):
        state.reset_session()
        st.rerun()

    conversation = state.get_conversation()
    turns = state.get_turns()

    pantry_request = components.render_pantry_panel(bot)
    if pantry_request:
        turns.append(handle_pantry(bot, pantry_request))
        st.rerun()

    if not turns:
        st.chat_message("assistant").write(
            "Hi! Tell me what ingredients you have and I'll find recipes "
            "from the database. For example: *what can I make with chicken, "
            "tomato and onion?*"
        )

    for turn in turns:
        components.render_turn(turn)

    message = st.chat_input("What ingredients do you have?")
    if not message:
        return

    # Echo immediately so the input doesn't feel dropped while we work.
    with st.chat_message("user"):
        st.write(message)

    with st.chat_message("assistant"):
        with st.spinner("Searching recipes…"):
            turn = handle_message(bot, conversation, message)
        if turn["error"]:
            st.error(turn["text"])
        else:
            st.write(turn["text"])
        components.render_recipes(turn)
        if turn.get("used_llm"):
            st.caption("Wording generated by an LLM from the recipes above.")

    turns.append(turn)


if __name__ == "__main__":
    main()
