"""Drive the real Chrome window through the LLM-enabled demo, on the clock.

Two differences from the template-only version:

* Gemini takes ~6s per turn, so each demo beat waits for the reply to
  actually appear (the UI stamps LLM-worded replies with a caption)
  rather than assuming a fixed delay.
* Demo beats get a larger trailing gap than code beats, so a reply has a
  moment on screen before the narration moves on.
"""
import json
import sys
import time
from pathlib import Path

from playwright.sync_api import sync_playwright

SCR = Path(sys.argv[1])
# argv may carry --warm, so pick the tempo by value, not position.
_nums = [a for a in sys.argv[2:] if not a.startswith("--")]
TEMPO = float(_nums[0]) if _nums else 1.06
CODE_GAP, DEMO_GAP = 0.30, 1.50
LLM_CAPTION = "text=Wording generated by an LLM"

man = json.loads((SCR / "manifest2.json").read_text())
MARKS, acc = [], 0.0
for seg in man:
    gap = DEMO_GAP if seg["anchor"].startswith("demo") else CODE_GAP
    acc += seg["dur"] / TEMPO + gap
    MARKS.append(acc)

CODE = f"file://{SCR}/code.html"
UI, API = "http://localhost:8501", "http://localhost:8000/docs"
t0 = None


def hold(i):
    target = t0 + MARKS[i]
    while time.time() < target:
        time.sleep(0.05)
    print(f"  {man[i]['anchor']:<15} done {time.time()-t0:6.2f}s "
          f"(target {MARKS[i]:6.2f})", flush=True)


def scroll_to(pg, anchor):
    pg.evaluate("""a => document.getElementById(a)
                   .scrollIntoView({behavior:'smooth', block:'start'})""",
                anchor)


def ask(pg, text, delay=40, wait_llm=True):
    """Send a message and wait for the reply to land."""
    before = pg.locator(LLM_CAPTION).count()
    box = pg.locator('textarea[data-testid="stChatInputTextArea"]')
    box.click()
    box.type(text, delay=delay)
    pg.keyboard.press("Enter")
    if not wait_llm:
        pg.wait_for_timeout(1200)
        return
    deadline = time.time() + 20
    while time.time() < deadline:
        if pg.locator(LLM_CAPTION).count() > before:
            pg.wait_for_timeout(400)
            return
        pg.wait_for_timeout(200)
    print(f"    (no LLM caption for {text!r} — fell back to template)",
          flush=True)


with sync_playwright() as pw:
    browser = pw.chromium.connect_over_cdp("http://localhost:9222")
    pg = browser.contexts[0].pages[0]

    if "--warm" in sys.argv:
        pg.goto(UI, wait_until="networkidle", timeout=120000)
        pg.wait_for_timeout(2500)
        try:
            pg.locator('button:has-text("Start over")').click()
            pg.wait_for_timeout(1500)
        except Exception as exc:
            print("  (no reset needed)", exc)
        pg.goto(API, wait_until="networkidle", timeout=120000)
        pg.wait_for_timeout(1500)
        pg.goto(CODE, wait_until="load")
        pg.wait_for_timeout(1200)
        print("WARM", flush=True)
        raise SystemExit(0)

    t0 = time.time()

    # ---- code ---------------------------------------------------------
    for i, anchor in enumerate(["overview", "engine", "guardrails",
                                "grounding", "provider", "verify"]):
        scroll_to(pg, anchor)
        hold(i)

    # ---- demo ---------------------------------------------------------
    pg.goto(UI, wait_until="domcontentloaded", timeout=60000)
    pg.wait_for_timeout(900)
    ask(pg, "what can I make with chicken, tomato and onion?")
    hold(6)

    ask(pg, "2", delay=90)
    ask(pg, "how do I make it?")
    hold(7)

    ask(pg, "Who is the president of India?", wait_llm=False)
    hold(8)

    have = pg.locator('[data-testid="stSidebar"] textarea')
    have.click()
    have.type("chicken, onion, tomato, garlic", delay=38)
    pg.keyboard.press("Tab")
    pg.wait_for_timeout(900)
    avoid = pg.locator('[data-testid="stSidebar"] input[type="text"]')
    avoid.click()
    avoid.type("cheese", delay=50)
    pg.keyboard.press("Tab")
    pg.wait_for_timeout(900)
    pg.locator('button:has-text("What can I make?")').click()
    pg.wait_for_timeout(2500)
    pg.evaluate("window.scrollTo({top:0, behavior:'smooth'})")
    hold(9)

    pg.goto(API, wait_until="domcontentloaded", timeout=60000)
    pg.wait_for_timeout(1200)
    try:
        pg.locator('span:has-text("/health")').first.click()
        pg.wait_for_timeout(600)
    except Exception as exc:
        print("  (swagger expand skipped)", exc)
    hold(10)

    print(f"\nfinished in {time.time()-t0:.2f}s (target {MARKS[-1]:.2f}s)")
